### ISSUE TITLE
Recursive Arrays

### ISSUE THREAD

**Issue by YStrauch** [sandorfr/gulp-swagger-generator#38]
Hello,

if you specify a an array within an array as followed:

```yaml
recursive_array:
        type: array
        items:
          type: array
          items:
            type: string
```

then the library will crash. I found the issue in the typescriptTypeMapper (and a quick fix):
```js
          else if (type === 'array') {
                /* The error occures because asArray() is not set for recursive arrays */
                return this.getType(property.items).asArray();

                /* Fix: A simple check if asArray is defined */
                if (!this.getType(property.items).asArray) {
                    return this.getType(property.items);
                }
                return this.getType(property.items).asArray();
            }
```

Hope I didn't miss something ;)
